### ISSUE TITLE
Cannot mint NFT in sepolia

### ISSUE THREAD

**Issue by edulanasca** [Quantum3-Labs/speedrunstark#22]
## Issue Overview

```
⚡️ ~ file: WriteOnlyFunctionForm.tsx:handleWrite ~ error ZodError: [
  {
    "code": "invalid_union",
    "unionErrors": [
      {
        "issues": [
          {
            "code": "invalid_union",
            "unionErrors": [
              {
                "issues": [
                  {
                    "code": "invalid_union",
                    "unionErrors": [
                      {
                        "issues": [
                          {
                            "code": "invalid_type",
                            "expected": "string",
                            "received": "object",
                            "path": [
                              0,
                              0,
                              "calldata",
                              1
                            ],
                            "message": "Expected string, received object"
                          }
                        ],
                        "name": "ZodError"
                      },
                      {
                        "issues": [
                          {
                            "code": "invalid_type",
                            "expected": "string",
                            "received": "object",
                            "path": [
                              0,
                              0,
                              "calldata",
                              1
                            ],
                            "message": "Expected string, received object"
                          }
                        ],
                        "name": "ZodError"
                      },
                      {
                        "issues": [
                          {
                            "code": "invalid_type",
                            "expected": "string",
                            "received": "object",
                            "path": [
                              0,
                              0,
                              "calldata",
                              1
                            ],
                            "message": "Expected string, received object"
                          }
                        ],
                        "name": "ZodError"
                      },
                      {
                        "issues": [
                          {
                            "code": "invalid_type",
                            "expected": "number",
                            "received": "object",
                            "path": [
                              0,
                              0,
                              "calldata",
                              1
                            ],
                            "message": "Expected number, received object"
                          }
                        ],
                        "name": "ZodError"
                      },
                      {
                        "issues": [
                          {
                            "code": "invalid_type",
                            "expected": "bigint",
                            "received": "object",
                            "path": [
                              0,
                              0,
                              "calldata",
                              1
                            ],
                            "message": "Expected bigint, received object"
                          }
                        ],
                        "name": "ZodError"
                      }
                    ],
                    "path": [
                      0,
                      0,
                      "calldata",
                      1
                    ],
                    "message": "Invalid input"
                  }
                ],
                "name": "ZodError"
              },
              {
                "issues": [
                  {
                    "code": "invalid_type",
                    "expected": "array",
                    "received": "object",
                    "path": [
                      0,
                      0,
                      "calldata",
                      1
                    ],
                    "message": "Expected array, received object"
                  }
                ],
                "name": "ZodError"
              }
            ],
            "path": [
              0,
              0,
              "calldata",
              1
            ],
            "message": "Invalid input"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "object",
            "received": "array",
            "path": [
              0
            ],
            "message": "Expected object, received array"
          }
        ],
        "name": "ZodError"
      }
    ],
    "path": [
      0
    ],
    "message": "Invalid input"
  }
]
    at get error (inpage.js:257:49713)
    at is.parseAsync (inpage.js:257:52179)
    at async OG.execute (inpage.js:2331:68667)
    at async Object.eval [as mutationFn] (index.js:1423:12)
```

## Proposed Solutions or Ideas

Outline your proposed solution or share any ideas you have for discussing or resolving the issue.

**Comment by edulanasca** [comment]
**NOTICE:** Only happens with **Argent** wallet

**Comment by 0xquantum3labs** [comment]
solved in main of `scaffold-stark-2` , at this [PR](https://github.com/Quantum3-Labs/scaffold-stark-2/pull/99)
